### ISSUE TITLE
ViewPropertyAnimator inconsistency between platforms

### ISSUE THREAD

**Issue by nalitzis** [JakeWharton/NineOldAndroids#26]
Hi Jake,

I've used ViewPropertyAnimator to simply move a button on the screen

``` java
ViewPropertyAnimator viewAnimator = animate(button);
viewAnimator.setDuration(1500);
viewAnimator.translationXBy(250);
viewAnimator.translationYBy(150);
viewAnimator.start();
```

on Android 3.x and above the button is tappable even after the animation has ended, while on Android 2.x it isn't.
I know that Android 2.x uses the old view animation system where the object actually doesn't move and you have to adjust its position in the callback. But can this be considered an inconsistency of the library? Should I write different code depending on the underlying animation system?

Thanks for your library! :)

**Comment by JakeWharton** [comment]
This is a fundamental limitation of the framework on pre-Honeycomb. The `View` class simply moves the area of the canvas on which controls draw during animations rather than moving where the view actually exists.

If you are moving a button with an animation and having it exist somewhere else for a long period of time (such that you can interact with it) you should be actually moving it to the destination location when the animation ends.

In any case, this is a platform restriction and there's nothing the library can do about it.
