### ISSUE TITLE
ViewHelper.setScaleX/Y breaks touch and redraw on android 2.3

### ISSUE THREAD

**Issue by kapuia** [JakeWharton/NineOldAndroids#55]
I'd like to use NineOldAndroid to scale complex views on android 2.3

Example
I have a view with one button. I scale down the view to to 0.5 both X/Y.
On older devices (2.3 or lower) the button cannot be clicked anymore (the hit area doesn't seem to follow the transformation), and layout falls into pieces. 

Is there anything we can do?

Thank you,
Akos

**Comment by JakeWharton** [comment]
This is a limitation of the pre-3.0 View rendering system. There's no easy way to work around this, sorry.

**Comment by kapuia** [comment]
Thanks for the fast response!

If we consider the hard way, could this be solved in a general way?
What is your opinion?

**Comment by JakeWharton** [comment]
The hard way would be a custom `ViewGroup` which intercepted touch events and remapped them to the object's new coordinate system based on the transformation `Matrix` that was currently applied. You could even do this by dynamically replacing the content view of an activity (`android.R.id.content`) dynamically without requiring the implementer to use this custom view group explicitly.

I spent about a day exploring this way, way back in the early days of this library. It turned out to be far too much work without a lot of payoff so I chose to abandon it.
